apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap
data:
  redis-config: |-
    protected-mode no
    bind 0.0.0.0
    port 6379
    {{- if .Values.master.password }}
    requirepass {{ .Values.master.password }}
    {{- end }}
    {{- if .Values.enableRedisTimeSeries }}
    loadmodule /opt/redis-stack/lib/redistimeseries.so
    {{- end }}    
