apiVersion: v1
kind: Service
metadata:
  name: {{ include "gabs-redis-harness.fullname" . }}
  labels:
    {{- include "gabs-redis-harness.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}      
  selector:
    {{- include "gabs-redis-harness.selectorLabels" . | nindent 4 }}


---

apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
spec:
  type: ClusterIP
  selector:
    {{- include "gabs-redis-harness.selectorLabels" . | nindent 4 }}
  ports:
  - name: redis-exporter
    protocol: TCP
    port: 9121
    targetPort: 9121
