# using NodePort this time until I get my domain back
service:
  type: NodePort
  port: 6379
  nodePort: 30099

# because we will roll with nginx ingress this time
#service:
#  type: ClusterIP
#  port: 6379

# now we use the nginx ingress - should I not hardcore the className ingress.class?
ingress:
  enabled: false
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  hosts:
    - host: redis.platformengineer.io
      paths:
        - path: /
          pathType: ImplementationSpecific
