# because we will roll with nginx ingress this time
service:
  type: ClusterIP
  port: 6379

# now we use the nginx ingress - should I not hardcore the className ingress.class?
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  hosts:
    - paths:
        - path: /redis
          pathType: Prefix
